### ISSUE TITLE
Installing debian.tgz using linuxdeploy on xiaomi mi2S (aries) fails to start

### ISSUE THREAD

**Issue by gaifeng8864** [DesktopECHO/linuxdeploy-images#1]
Dear DesktopECHO, I'm very sorry to take up your precious time. First of all thank you very much for your contribution to linux on android.
I want to install klipper to android, but it requires systemctl by default. I was looking at you here https://www.reddit.com/r/Android/comments/v13er2/linux_deploy_on_android_when_you_cant_find_a/
After the post, I learned that you packaged a debian version that supports sytemctl, so I followed your steps on youtube to install it.
My device is xiaomi mi2S (aries) and the android system is "MOKEE MK90.0-aries-210620-HISTORY.zip". I have gained root.
At first, the installation went well, but after the installation and then restarting, it will get stuck in a step called "Android-ini...", and the phone will automatically shut down immediately. I've tried multiple installs with different configurations, even using ncd12.tgz, but it's all the same.
Is it a device compatibility issue? Can you help me repackage a new debian11 system that supports systemctl?
Or if you can help me provide some packaging methods for debian systems that support systemctl, I would be more grateful.

**Comment by DesktopECHO** [comment]
See this [post on XDA](https://forum.xda-developers.com/t/app-tool-2-0-official-the-selinux-switch.3656502/) for an APK to disable SELinux.  That might be your issue.

**Comment by gaifeng8864** [comment]
> See this [post on XDA](https://forum.xda-developers.com/t/app-tool-2-0-official-the-selinux-switch.3656502/) for an APK to disable SELinux. That might be your issue.

thank you for your reply.
I installed the software and the software showed my SELINUX mode as Permissive. And I checked it with the getenforce command in termux, and the returned information is also Permissive.

**Comment by gaifeng8864** [comment]
> See this [post on XDA](https://forum.xda-developers.com/t/app-tool-2-0-official-the-selinux-switch.3656502/) for an APK to disable SELinux. That might be your issue.

I re-installed using your latest release https://github.com/DesktopECHO/linuxdeploy-images/raw/main/debian.tgz and followed the instructions exactly https://github.com/DesktopECHO/linuxdeploy-images/ blob/main/README.md.
However, the phone still automatically shuts down when it is restarted after the installation is complete. But I noticed one thing: the phone didn't shut down completely, it left an F drive on my computer with a folder named "image" in it. There are some files in there, I'll show them in the picture.
![1](https://user-images.githubusercontent.com/16047447/197475812-5fd4b3b2-f7ee-427c-9cdc-acb25ad48a60.PNG)

![2](https://user-images.githubusercontent.com/16047447/197475976-d2feb641-84a8-4d17-a97a-c66cb553c658.PNG)

**Comment by gaifeng8864** [comment]
> See this [post on XDA](https://forum.xda-developers.com/t/app-tool-2-0-official-the-selinux-switch.3656502/) for an APK to disable SELinux. That might be your issue.

I downloaded debian.tgz and re-installed it. When I booted to the steps in the picture below, the phone still shuts down automatically. Other conditions are the same as before.
![3](https://user-images.githubusercontent.com/16047447/197483665-8c85dcc6-8593-4836-966a-a5864947fc2a.png)

**Comment by DesktopECHO** [comment]
H there, question for you --
In Linux Deploy "Installation Type" did you select 'File' or 'Partition' ?
(File should be ok, Partition may trigger a reboot)

**Comment by gaifeng8864** [comment]
> H there, question for you -- In Linux Deploy "Installation Type" did you select 'File' or 'Partition' ? (File should be ok, Partition may trigger a reboot)

"file" and "image file" have been used, the same phenomenon. But "partition" is not used.

**Comment by gaifeng8864** [comment]
If it is not easy to locate the reason, can you guide me how to install systemd-shim from source in debian system? I have searched the Internet for a long time, but did not get enough information on how to compile and install. I'm really sorry to bother you all the time, but I really can't figure it out myself, and there's no one around to help me, so I can only bother you.

**Comment by DesktopECHO** [comment]
Try this Raspbian APK I just created and see if you have any luck:
https://github.com/DesktopECHO/Pi-hole-for-Android/releases/tag/v3.0.0

Or, on your own Debian image, put this in `/etc`
https://github.com/DesktopECHO/xWSL/raw/master/dist/etc/systemctl-service-shim.tar

Then run this at startup: (as root)
`rm /usr/bin/systemctl ; cd / ; tar xf /etc/systemctl-service-shim.tar`

**Comment by gaifeng8864** [comment]
> 



> Try this Raspbian APK I just created and see if you have any luck: https://github.com/DesktopECHO/Pi-hole-for-Android/releases/tag/v3.0.0
> 
> Or, on your own Debian image, put this in `/etc` https://github.com/DesktopECHO/xWSL/raw/master/dist/etc/systemctl-service-shim.tar
> 
> Then run this at startup: (as root) `rm /usr/bin/systemctl ; cd / ; tar xf /etc/systemctl-service-shim.tar`

ok, i'll try it, thanks a lot.

**Comment by gaifeng8864** [comment]
> Try this Raspbian APK I just created and see if you have any luck: https://github.com/DesktopECHO/Pi-hole-for-Android/releases/tag/v3.0.0
> 
> Or, on your own Debian image, put this in `/etc` https://github.com/DesktopECHO/xWSL/raw/master/dist/etc/systemctl-service-shim.tar
> 
> Then run this at startup: (as root) `rm /usr/bin/systemctl ; cd / ; tar xf /etc/systemctl-service-shim.tar`

After my repeated tests, I finally succeeded after using the "MOKEE" system with the kernel "android 7". The "debian.tgz" you recently released works well on the original version of linuxdeploy, and the physical machine is xiaomi 2S. Thank you again.

**Comment by DesktopECHO** [comment]
Great news, good luck with it!
