### ISSUE TITLE
Is possible get CentOS for old Android

### ISSUE THREAD

**Issue by Jeffsa12** [DesktopECHO/linuxdeploy-images#4]
Hello Sir, I want to thank you for your efforts in all your projects available to all of us, I also want to ask you if it is possible to help me with centOS image rootfs, for android 4.4 to test Adguard HOME, with the conatruded pi-hole image it is not possible to run the software due to port occupation by pi-hole and upon uninstalling it no longer allows Adguar to be used. Thanks for any response

**Comment by DesktopECHO** [comment]
> it no longer allows Adguar to be used.

What do you mean by this?  
If Pi-hole is uninstalled there should not be anything preventing you from installing some other product.

**Comment by Jeffsa12** [comment]
Thanks for responding, it seems that deleting pi-hole centOS leaves you without accessible DNS, however I am trying to adjust them from LinuxDeploy settings to see if it is possible to use the service
![Screenshot_20240516-170154_ConnectBot](https://github.com/DesktopECHO/linuxdeploy-images/assets/170038419/29437c72-f996-4962-b54c-5b8d077946ee)

**Comment by DesktopECHO** [comment]
This will change the nameserver in resolv.conf:

`sudo echo "nameserver 1.1.1.1" > /etc/resolv.conf`

Then see if `curl` works.

**Comment by Jeffsa12** [comment]
Now it's working, thank you a lot of. Only I have a little problem now with static ip, the android has one. But when I stop LinuxDeploy and restart isn't possible access to Web page of Adguard. Is possible that you can help me?

**Comment by Jeffsa12** [comment]
Thank you very much sir, everything is working now it was necessary to configure the different networks, at this moment everything seems in order, as at the beginning, thank you for providing us with support and these wonderful tools.
